name: secrekey
description: A Secret Key Generator
publish_to: "none"
version: 2.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  get: ^4.6.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.8
  permission_handler: ^8.3.0

dev_dependencies:
  analyzer: ^2.1.0
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.3.2
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  mockito: ^5.0.16

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
