name: secrekey
description: A Secret Key Generator
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  encrypt: ^5.0.1
  equatable: ^2.0.3
  get_it: ^7.2.0
  get_storage: ^2.0.3
  firebase_core: ^1.10.6
  firebase_crashlytics: ^2.4.4
  flutter_bloc: ^8.0.0
  path_provider: ^2.0.8
  permission_handler: ^8.3.0
  sqflite_sqlcipher: ^2.1.0
  sqflite_common_porter:
    git:
      url: https://github.com/tekartik/sqflite_more
      ref: dart2_3
      path: sqflite_common_porter
      version: '>=0.2.0'

dev_dependencies:
  analyzer: ^2.1.0
  bloc_test: ^9.0.1
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.4
  flutter_native_splash: ^1.3.2
  mockito: ^5.0.16
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700